name: "Bug Report best"
description: Report a bug to help improve the project.
title: "bug: "
labels: type/bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!

        The more information you share, the faster we can identify and fix the bug.

        Prior to opening the issue, please make sure that you:

        - Use English to communicate.
        - Search the [open issues](https://github.com/ohxinru/XR/issues) to avoid duplicating the issue.
  
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the issue you are facing.
      placeholder: |
        What is the issue with the current behavior?
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: |
        What did you expect to happen instead?
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Share the steps you took so that we can reproduce the issue. Reports without proper steps details will likely be closed.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Share your environment details. Reports without proper environment details will likely be closed.
      value: |
        - Device <!-- e.g. mac, iphone6 -->:
        - OS: [e.g. iOS,iOS8.1]:
        - Browser [e.g. chrome, safari]:
        - Enviroment [e.g. integration, staging, production]:
        - Version ( e.g. v0.13.7)::
    validations:
      required: true
  - type: textarea
    id: error
    attributes:
      label: Error Logs
      description: Paste the error logs if any. 
    validations:
      required: false
  - type: textarea
    id: Screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
