name: "📚 Documentation Issue"
description: 与文档相关的需求。
title: "docs: "
labels: type/documentation
body:
  - type: markdown
    attributes:
      value: |
        **你提供的信息越多，我们就能越快的帮助你实现需求。**

        在打开issue之前,请确保你:

        - 搜索 [open issues](https://github.com/vikadata/vikadata/issues) 来查找有没有类似问题,以避免重复。
        - 确保按documentation模版补充完整相关信息。

  - type: textarea
    id: description
    attributes: 
      label: 描述
      description: 清晰简洁地描述文档包含什么内容，解决什么问题。
      placeholder: |
        此文档主要包含什么内容，解决什么问题
    validations:
      required: true
